-- Mac模拟器的设置
MAC_SIMULATOR_WINDOW_WIDTH  = 768
MAC_SIMULATOE_WINDOW_HEIGHT = 1024
MAC_SIMULATOR_WINDOW_SCALE  = 0.5
MAC_SIMULATOR_RESOLUTION_WIDTH  = 640
MAC_SIMULATOR_RESOLUTION_HEIGHT = 960

GAME_FPS = 60