-- Mac模拟器的设置
MAC_SIMULATOR_WINDOW_WIDTH  = 768
MAC_SIMULATOE_WINDOW_HEIGHT = 1024
MAC_SIMULATOR_WINDOW_SCALE  = 0.5
MAC_SIMULATOR_RESOLUTION_WIDTH  = 640
MAC_SIMULATOR_RESOLUTION_HEIGHT = 960

GAME_FPS = 60

-- 总藤蔓数
VINE_COUNT = 20
-- 速率控制
VINE_SPEED_FACTOR = 10

-- 分段的一些参数
VINE_PART_INTERVAL = 1   -- 产生间隔，同时也影响老化
VINE_PART_LIFESPAN = 20  -- 生命周期
VINE_PART_GROWUP_TIME = 5  -- 生长期的时间
VINE_PART_SHRINK_TIME = 5  -- 萎缩期的时间
VINE_PART_SHRINK_SCALE = 0.7  -- 萎缩期到最终的scale
VINE_PART_DEFLECTION_ANGLE = 35  -- 强制偏折角度范围